name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  api-tests:
    # run inside a Docker container based on the official Node image
    name: API Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy
    # matrix not needed when using fixed container image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: |
          # run only spec files under tests/api-tests
          npx playwright test tests/api-tests/**
        env:
          CI: true
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run UI tests
        run: |
          # run only spec files under tests/ui-test
          npx playwright test tests/ui-tests/**
        env:
          CI: true
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: |
          npx playwright test --project=chromium
        env:
          CI: true
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}

      # optionally upload Playwright report if needed
      - name: Archive Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright--ui-report
          path: playwright-report/
